version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      TZ: 'GMT'
      PGTZ: 'GMT'
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: youthgame
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_1
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    links:
      - postgres

volumes:
  postgres:
    driver: local
